### ISSUE TITLE
Load Rom - /media/fat/games/A.Flicky/a.flicky.rom (not working)

### ISSUE THREAD

**Issue by wwark** [MrX-8B/MiSTer-Arcade-Flicky#1]
Hi,
Just for information, we need to put a.flicky.rom in this directory "/media/fat/bootrom" to be able to play Flicky.
Other cores we can play rom using /media/fat/games/A.xxx/a.xxx.rom without needed to put a.xxx.rom in this directory "/media/fat/bootrom". In this case we use Load Rom.

Thanks for the fix !

**Comment by MrX-8B** [comment]
Thank you for your report.

Can you tell me exactly which other cores are working properly in your environment?
It would be helpful if you could enumerate about three.

**Comment by wwark** [comment]
All you other cores like digdug, atetris, druaga. No need to have rom in bootrom directory.
Thank you.

**Comment by MrX-8B** [comment]
After updating to the latest system (19/12/05), my environment was also in bad condition, but I formatted the SD card and tried to set it up again.

As a result, on latest system, the core does not seem to boot directly even if games/A.xxx/a.xxx.rom is available.
You can start it using the OSD's load ROM.

Start directly with the root of the SD card or have bootrom/a.xxx.rom like you.

It seems that there is something wrong with MiSTer's system side, not the arcade core, because it is the same not only with the arcade core that I made but also the arcade core made by others.

**Comment by wwark** [comment]
Ok thank you for the update.
We have to wait some fixes on main mister side. There is also MRA files will arrive soon so better to wait.
I close this ticket and see the next changes on main mister !
